name: Shell commands

on: workflow_dispatch #[push]

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello, Security Gurus! This is our First GitHub Action"
